### ISSUE TITLE
webm url replacement has null error

### ISSUE THREAD

**Issue by FridayAnubis** [clragon/e1547#103]
"id order" option in favorite tab works, but it keeps loading when switch to "added order" mode.

**Error log:**

```
Critical | 13:39:53.965 | Flutter: Flutter: Null check operator used on a null value
╔ Error ═══════════════════════════════════════════════════════════════════════════════════╗
║
║  #0      Post.file (package:e1547/post/data/post.dart:47)
║  #1      FavoritePostsController.fetch.<anonymous closure> (package:e1547/post/data/favorites.dart:51)
║  #2      ListBase._filter (dart:collection/list.dart:293)
║  #3      ListBase.removeWhere (dart:collection/list.dart:281)
║  #4      FavoritePostsController.fetch (package:e1547/post/data/favorites.dart:51)
║  <asynchronous suspension>
║  #5      PageClientDataController.requestPage.<anonymous closure> (package:e1547/client/data/controller.dart:54)
║  <asynchronous suspension>
║  #6      ClientDataController.withError (package:e1547/client/data/controller.dart:38)
║  <asynchronous suspension>
║  #7      FavoritePostsController.withError (package:e1547/post/data/favorites.dart:60)
║  <asynchronous suspension>
║  #8      DataController.loadPage.<anonymous closure> (package:e1547/interface/data/controller.dart:68)
║  <asynchronous suspension>
║  #9      PageLock.protect (package:e1547/interface/data/controller.dart:265)
║  <asynchronous suspension>
║  #10     DataController.loadPage (package:e1547/interface/data/controller.dart:54)
║  <asynchronous suspension>
║  
║
╚══════════════════════════════════════════════════════════════════════════════════════════╝
```

**APP version:**

16.2.0

**Device information:**

iPhone13PM, iOS 15.7.1

**Comment by clragon** [comment]
thank you for reporting this issue. 
it will be fixed in the next update.
