### ISSUE TITLE
_OneByteString JSON error

### ISSUE THREAD

**Issue by TLCPlusPlus** [clragon/e1547#90]
```
ERROR | 17:01:05.363

type '_OneByteString' is not a subtype of type 'FutureOr<Map<String, dynamic>>'

StackTrace: #0      Client.postsRaw.<anonymous closure> (package:e1547/client/data/client.dart:127)
<asynchronous suspension>
#1      Client.postsRaw (package:e1547/client/data/client.dart:113)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:522)
<asynchronous suspension>
#3      FollowsUpdater._updateFollows (package:e1547/follow/data/updater.dart:128)
<asynchronous suspension>
#4      FollowsUpdater.update (package:e1547/follow/data/updater.dart:79)
<asynchronous suspension>
#5      _StartupActionsState.initState.<anonymous closure>.<anonymous closure> (package:e1547/interface/widgets/startup.dart:35)
<asynchronous suspension>
}
```

**Comment by clragon** [comment]
this error occurs when the site is down.
unfortunately, the way the site makes it known that it is down is not very friendly for API clients.
